theme = "."
baseurl = "/"
languageCode = "en-us"
title = "Nederland Greenhouse"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "../docs"
themesDir = "../.."

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "volunteer saturdays"
    url = "/volunteer/"
    pre = "<i class='now-ui-icons design_app'></i>"
    weight = 1
[[menu.main]]
    name = "Programs"
    url = "/programming/"
    pre = "<i class='now-ui-icons business_bank'></i>"
    weight = 1
[[menu.main]]
    name = "Food Security"
    url = "/food-security/"
    pre = "<i class='now-ui-icons users_single-02'></i>"
    weight = 2
[[menu.main]]
    name = "Signup"
    pre = "<i class='now-ui-icons clothes_tie-bow'></i>"
    url = "/login/"
    weight = 3
[[menu.main]]
    name = "Community Build Process"
    pre = "<i class='now-ui-icons ui-1_settings-gear-63'></i>"
    url = "#"
    weight = 4
    identifier = "dropdown"
[[menu.main]]
    name = "Timberframe Log Prep"
    pre = "<i class='now-ui-icons files_paper'></i>"
    url = "/timberframe/"
    weight = 1
    parent = "dropdown"
[[menu.main]]
    name = "Rubble Trench Foundations"
    pre = "<i class='now-ui-icons ui-1_calendar-60'></i>"
    url = "/foundation/"
    weight = 2
    parent = "dropdown"
[[menu.main]]
    name = "Thermal Mass & South Facing Glass"
    pre = "<i class='now-ui-icons shopping_tag-content'></i>"
    url = "/glass/"
    weight = 2
    parent = "dropdown"    
    
[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/cboettig"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/cboettig"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3


[params]
    background = "/img/bg11.jpg"
    tint = "yellow"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A community greenhouse and eco building demonstration projectlead by Earth Hop Designs in Nederland, Colorado USA, Novembner 2018."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"


    

