theme = "."
baseurl = "/"
languageCode = "en-us"
title = "Nederland Greenhouse Project"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Our Team"
    url = "/team/"
    pre = "<i class='now-ui-icons ui-2_chat-round'></i>"
    weight = 1
[[menu.main]]
    name = "Upcoming Events"
    url = "/events/"
    pre = "<i class='now-ui-icons business_bulb-63'></i>"
    weight = 2
[[menu.main]]
    name = "Community Build Process"
    pre = "<i class='now-ui-icons objects_planet'></i>"
    url = "/cbp/"
    weight = 3
[[menu.main]]
    name = "Resources"
    pre = "<i class='now-ui-icons ui-1_settings-gear-63'></i>"
    url = "/resources/"
    weight = 4
[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/cboettig"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/cboettig"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "(C) 2019 Ned Greenhouse, Web by donation: SCD Hub using Hugo & Netlify"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3


[params]
    background = "/img/pics/veggies.jpg"
    tint = "yellow"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "Nederland’s community greenhouse is a showcase of high altitude food sovereignty. The structure is made from reclaimed and locally sourced materials such as pavement rubble from Boulder and timber frames sourced from a local fire mitigation site. The heating mechanism is a heat transfer system, an off grid technology made with solar collectors, thermostat sensors, steel drums and radiant floor pipes. Once we reach our fundraising goals, this will be a repeatable off grid four season greenhouse that folks can build in other locations for greater food sovereignty. Check back here to learn about the greenhouse construction plans to build your own, get involved with upcoming fundraisers and action days and for free resources on alpine gardening."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"


    

